/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 47
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 37
#define ALIAS_COUNT 0
#define TOKEN_COUNT 19
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LBRACK = 1,
  anon_sym_RBRACK = 2,
  sym_title_key = 3,
  sym_artist_key = 4,
  sym_length_key = 5,
  sym_author_key = 6,
  anon_sym_re_COLON = 7,
  anon_sym_tool_COLON = 8,
  sym_album_key = 9,
  sym_offset_key = 10,
  sym_by_key = 11,
  sym_lyricist_key = 12,
  aux_sym_value_token1 = 13,
  sym_length_value = 14,
  sym_offset_value = 15,
  sym_timestamp = 16,
  sym_comment = 17,
  sym__eol = 18,
  sym_source_file = 19,
  sym_header = 20,
  sym_id_tag = 21,
  sym_title_tag = 22,
  sym_artist_tag = 23,
  sym_album_tag = 24,
  sym_length_tag = 25,
  sym_lyricist_tag = 26,
  sym_offset_tag = 27,
  sym_author_tag = 28,
  sym_tool_tag = 29,
  sym_by_tag = 30,
  sym_time_tag = 31,
  sym_tool_key = 32,
  sym_value = 33,
  sym_lyrics = 34,
  aux_sym_source_file_repeat1 = 35,
  aux_sym_header_repeat1 = 36,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [sym_title_key] = "title_key",
  [sym_artist_key] = "artist_key",
  [sym_length_key] = "length_key",
  [sym_author_key] = "author_key",
  [anon_sym_re_COLON] = "re:",
  [anon_sym_tool_COLON] = "tool:",
  [sym_album_key] = "album_key",
  [sym_offset_key] = "offset_key",
  [sym_by_key] = "by_key",
  [sym_lyricist_key] = "lyricist_key",
  [aux_sym_value_token1] = "value_token1",
  [sym_length_value] = "length_value",
  [sym_offset_value] = "offset_value",
  [sym_timestamp] = "timestamp",
  [sym_comment] = "comment",
  [sym__eol] = "_eol",
  [sym_source_file] = "source_file",
  [sym_header] = "header",
  [sym_id_tag] = "id_tag",
  [sym_title_tag] = "title_tag",
  [sym_artist_tag] = "artist_tag",
  [sym_album_tag] = "album_tag",
  [sym_length_tag] = "length_tag",
  [sym_lyricist_tag] = "lyricist_tag",
  [sym_offset_tag] = "offset_tag",
  [sym_author_tag] = "author_tag",
  [sym_tool_tag] = "tool_tag",
  [sym_by_tag] = "by_tag",
  [sym_time_tag] = "time_tag",
  [sym_tool_key] = "tool_key",
  [sym_value] = "value",
  [sym_lyrics] = "lyrics",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_header_repeat1] = "header_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [sym_title_key] = sym_title_key,
  [sym_artist_key] = sym_artist_key,
  [sym_length_key] = sym_length_key,
  [sym_author_key] = sym_author_key,
  [anon_sym_re_COLON] = anon_sym_re_COLON,
  [anon_sym_tool_COLON] = anon_sym_tool_COLON,
  [sym_album_key] = sym_album_key,
  [sym_offset_key] = sym_offset_key,
  [sym_by_key] = sym_by_key,
  [sym_lyricist_key] = sym_lyricist_key,
  [aux_sym_value_token1] = aux_sym_value_token1,
  [sym_length_value] = sym_length_value,
  [sym_offset_value] = sym_offset_value,
  [sym_timestamp] = sym_timestamp,
  [sym_comment] = sym_comment,
  [sym__eol] = sym__eol,
  [sym_source_file] = sym_source_file,
  [sym_header] = sym_header,
  [sym_id_tag] = sym_id_tag,
  [sym_title_tag] = sym_title_tag,
  [sym_artist_tag] = sym_artist_tag,
  [sym_album_tag] = sym_album_tag,
  [sym_length_tag] = sym_length_tag,
  [sym_lyricist_tag] = sym_lyricist_tag,
  [sym_offset_tag] = sym_offset_tag,
  [sym_author_tag] = sym_author_tag,
  [sym_tool_tag] = sym_tool_tag,
  [sym_by_tag] = sym_by_tag,
  [sym_time_tag] = sym_time_tag,
  [sym_tool_key] = sym_tool_key,
  [sym_value] = sym_value,
  [sym_lyrics] = sym_lyrics,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_header_repeat1] = aux_sym_header_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [sym_title_key] = {
    .visible = true,
    .named = true,
  },
  [sym_artist_key] = {
    .visible = true,
    .named = true,
  },
  [sym_length_key] = {
    .visible = true,
    .named = true,
  },
  [sym_author_key] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_re_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_tool_COLON] = {
    .visible = true,
    .named = false,
  },
  [sym_album_key] = {
    .visible = true,
    .named = true,
  },
  [sym_offset_key] = {
    .visible = true,
    .named = true,
  },
  [sym_by_key] = {
    .visible = true,
    .named = true,
  },
  [sym_lyricist_key] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_value_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_length_value] = {
    .visible = true,
    .named = true,
  },
  [sym_offset_value] = {
    .visible = true,
    .named = true,
  },
  [sym_timestamp] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym__eol] = {
    .visible = false,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_header] = {
    .visible = true,
    .named = true,
  },
  [sym_id_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_title_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_artist_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_album_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_length_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_lyricist_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_offset_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_author_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_tool_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_by_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_time_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_tool_key] = {
    .visible = true,
    .named = true,
  },
  [sym_value] = {
    .visible = true,
    .named = true,
  },
  [sym_lyrics] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_header_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(43);
      ADVANCE_MAP(
        '\n', 62,
        '\r', 1,
        '#', 61,
        '[', 44,
        ']', 45,
        'a', 26,
        'b', 33,
        'l', 18,
        'o', 22,
        'r', 20,
        't', 25,
        '\t', 2,
        ' ', 2,
        '+', 35,
        '-', 35,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(41);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(62);
      END_STATE();
    case 2:
      ADVANCE_MAP(
        '\n', 62,
        '\r', 1,
        '#', 61,
        '[', 44,
        ']', 45,
        'a', 26,
        'b', 33,
        'l', 18,
        'o', 22,
        'r', 20,
        't', 25,
        '\t', 2,
        ' ', 2,
        '+', 35,
        '-', 35,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(41);
      END_STATE();
    case 3:
      if (lookahead == '.') ADVANCE(40);
      END_STATE();
    case 4:
      if (lookahead == ':') ADVANCE(52);
      END_STATE();
    case 5:
      if (lookahead == ':') ADVANCE(47);
      END_STATE();
    case 6:
      if (lookahead == ':') ADVANCE(49);
      END_STATE();
    case 7:
      if (lookahead == ':') ADVANCE(54);
      END_STATE();
    case 8:
      if (lookahead == ':') ADVANCE(55);
      END_STATE();
    case 9:
      if (lookahead == ':') ADVANCE(50);
      END_STATE();
    case 10:
      if (lookahead == ':') ADVANCE(46);
      END_STATE();
    case 11:
      if (lookahead == ':') ADVANCE(34);
      END_STATE();
    case 12:
      if (lookahead == ':') ADVANCE(51);
      END_STATE();
    case 13:
      if (lookahead == ':') ADVANCE(48);
      END_STATE();
    case 14:
      if (lookahead == ':') ADVANCE(53);
      END_STATE();
    case 15:
      if (lookahead == ':') ADVANCE(39);
      END_STATE();
    case 16:
      if (lookahead == ']') ADVANCE(60);
      END_STATE();
    case 17:
      if (lookahead == ']') ADVANCE(60);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(16);
      END_STATE();
    case 18:
      if (lookahead == 'e') ADVANCE(28);
      if (lookahead == 'r') ADVANCE(8);
      END_STATE();
    case 19:
      if (lookahead == 'e') ADVANCE(32);
      END_STATE();
    case 20:
      if (lookahead == 'e') ADVANCE(9);
      END_STATE();
    case 21:
      if (lookahead == 'f') ADVANCE(30);
      END_STATE();
    case 22:
      if (lookahead == 'f') ADVANCE(21);
      END_STATE();
    case 23:
      if (lookahead == 'g') ADVANCE(31);
      END_STATE();
    case 24:
      if (lookahead == 'h') ADVANCE(13);
      END_STATE();
    case 25:
      if (lookahead == 'i') ADVANCE(10);
      if (lookahead == 'o') ADVANCE(29);
      END_STATE();
    case 26:
      if (lookahead == 'l') ADVANCE(4);
      if (lookahead == 'r') ADVANCE(5);
      if (lookahead == 'u') ADVANCE(6);
      END_STATE();
    case 27:
      if (lookahead == 'l') ADVANCE(12);
      END_STATE();
    case 28:
      if (lookahead == 'n') ADVANCE(23);
      END_STATE();
    case 29:
      if (lookahead == 'o') ADVANCE(27);
      END_STATE();
    case 30:
      if (lookahead == 's') ADVANCE(19);
      END_STATE();
    case 31:
      if (lookahead == 't') ADVANCE(24);
      END_STATE();
    case 32:
      if (lookahead == 't') ADVANCE(14);
      END_STATE();
    case 33:
      if (lookahead == 'y') ADVANCE(7);
      END_STATE();
    case 34:
      if (('0' <= lookahead && lookahead <= '5')) ADVANCE(37);
      END_STATE();
    case 35:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(59);
      END_STATE();
    case 36:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(58);
      END_STATE();
    case 37:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(3);
      END_STATE();
    case 38:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(17);
      END_STATE();
    case 39:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(36);
      END_STATE();
    case 40:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(38);
      END_STATE();
    case 41:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(15);
      END_STATE();
    case 42:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(11);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(42);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_title_key);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_artist_key);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_length_key);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_author_key);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_re_COLON);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_tool_COLON);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_album_key);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_offset_key);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_by_key);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_lyricist_key);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(aux_sym_value_token1);
      if (lookahead == '#') ADVANCE(57);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(56);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ']') ADVANCE(57);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(aux_sym_value_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ']') ADVANCE(57);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_length_value);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_offset_value);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(59);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_timestamp);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ']') ADVANCE(61);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym__eol);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 56},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 56},
  [24] = {.lex_state = 56},
  [25] = {.lex_state = 56},
  [26] = {.lex_state = 56},
  [27] = {.lex_state = 56},
  [28] = {.lex_state = 56},
  [29] = {.lex_state = 56},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 56},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [sym_title_key] = ACTIONS(1),
    [sym_artist_key] = ACTIONS(1),
    [sym_length_key] = ACTIONS(1),
    [sym_author_key] = ACTIONS(1),
    [anon_sym_re_COLON] = ACTIONS(1),
    [anon_sym_tool_COLON] = ACTIONS(1),
    [sym_album_key] = ACTIONS(1),
    [sym_offset_key] = ACTIONS(1),
    [sym_by_key] = ACTIONS(1),
    [sym_lyricist_key] = ACTIONS(1),
    [sym_length_value] = ACTIONS(1),
    [sym_offset_value] = ACTIONS(1),
    [sym_timestamp] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [sym__eol] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(30),
    [sym_header] = STATE(5),
    [sym_id_tag] = STATE(6),
    [sym_title_tag] = STATE(8),
    [sym_artist_tag] = STATE(8),
    [sym_album_tag] = STATE(8),
    [sym_length_tag] = STATE(8),
    [sym_lyricist_tag] = STATE(8),
    [sym_offset_tag] = STATE(8),
    [sym_author_tag] = STATE(8),
    [sym_tool_tag] = STATE(8),
    [sym_by_tag] = STATE(8),
    [sym_time_tag] = STATE(45),
    [aux_sym_source_file_repeat1] = STATE(7),
    [aux_sym_header_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_LBRACK] = ACTIONS(7),
    [sym_timestamp] = ACTIONS(9),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LBRACK,
    STATE(3), 1,
      aux_sym_header_repeat1,
    STATE(6), 1,
      sym_id_tag,
    ACTIONS(11), 2,
      ts_builtin_sym_end,
      sym_timestamp,
    STATE(8), 9,
      sym_title_tag,
      sym_artist_tag,
      sym_album_tag,
      sym_length_tag,
      sym_lyricist_tag,
      sym_offset_tag,
      sym_author_tag,
      sym_tool_tag,
      sym_by_tag,
  [28] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    STATE(3), 1,
      aux_sym_header_repeat1,
    STATE(6), 1,
      sym_id_tag,
    ACTIONS(13), 2,
      ts_builtin_sym_end,
      sym_timestamp,
    STATE(8), 9,
      sym_title_tag,
      sym_artist_tag,
      sym_album_tag,
      sym_length_tag,
      sym_lyricist_tag,
      sym_offset_tag,
      sym_author_tag,
      sym_tool_tag,
      sym_by_tag,
  [56] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(18), 1,
      sym_title_key,
    ACTIONS(20), 1,
      sym_artist_key,
    ACTIONS(22), 1,
      sym_length_key,
    ACTIONS(24), 1,
      sym_author_key,
    ACTIONS(28), 1,
      sym_album_key,
    ACTIONS(30), 1,
      sym_offset_key,
    ACTIONS(32), 1,
      sym_by_key,
    ACTIONS(34), 1,
      sym_lyricist_key,
    STATE(21), 1,
      sym_tool_key,
    ACTIONS(26), 2,
      anon_sym_re_COLON,
      anon_sym_tool_COLON,
  [91] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      sym_timestamp,
    ACTIONS(36), 1,
      ts_builtin_sym_end,
    STATE(9), 1,
      aux_sym_source_file_repeat1,
    STATE(45), 1,
      sym_time_tag,
  [107] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(40), 1,
      anon_sym_LBRACK,
    ACTIONS(42), 1,
      sym__eol,
    ACTIONS(38), 2,
      ts_builtin_sym_end,
      sym_timestamp,
  [121] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      sym_timestamp,
    ACTIONS(36), 1,
      ts_builtin_sym_end,
    STATE(10), 1,
      aux_sym_source_file_repeat1,
    STATE(45), 1,
      sym_time_tag,
  [137] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(46), 1,
      anon_sym_LBRACK,
    ACTIONS(44), 3,
      ts_builtin_sym_end,
      sym_timestamp,
      sym__eol,
  [149] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      sym_timestamp,
    ACTIONS(48), 1,
      ts_builtin_sym_end,
    STATE(10), 1,
      aux_sym_source_file_repeat1,
    STATE(45), 1,
      sym_time_tag,
  [165] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(50), 1,
      ts_builtin_sym_end,
    ACTIONS(52), 1,
      sym_timestamp,
    STATE(10), 1,
      aux_sym_source_file_repeat1,
    STATE(45), 1,
      sym_time_tag,
  [181] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(57), 1,
      anon_sym_LBRACK,
    ACTIONS(55), 3,
      ts_builtin_sym_end,
      sym_timestamp,
      sym__eol,
  [193] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(61), 1,
      anon_sym_LBRACK,
    ACTIONS(59), 3,
      ts_builtin_sym_end,
      sym_timestamp,
      sym__eol,
  [205] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(65), 1,
      anon_sym_LBRACK,
    ACTIONS(63), 3,
      ts_builtin_sym_end,
      sym_timestamp,
      sym__eol,
  [217] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(69), 1,
      anon_sym_LBRACK,
    ACTIONS(67), 3,
      ts_builtin_sym_end,
      sym_timestamp,
      sym__eol,
  [229] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(73), 1,
      anon_sym_LBRACK,
    ACTIONS(71), 3,
      ts_builtin_sym_end,
      sym_timestamp,
      sym__eol,
  [241] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(77), 1,
      anon_sym_LBRACK,
    ACTIONS(75), 3,
      ts_builtin_sym_end,
      sym_timestamp,
      sym__eol,
  [253] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(81), 1,
      anon_sym_LBRACK,
    ACTIONS(79), 3,
      ts_builtin_sym_end,
      sym_timestamp,
      sym__eol,
  [265] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(85), 1,
      anon_sym_LBRACK,
    ACTIONS(83), 3,
      ts_builtin_sym_end,
      sym_timestamp,
      sym__eol,
  [277] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(89), 1,
      anon_sym_LBRACK,
    ACTIONS(87), 3,
      ts_builtin_sym_end,
      sym_timestamp,
      sym__eol,
  [289] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(91), 1,
      anon_sym_LBRACK,
    ACTIONS(13), 2,
      ts_builtin_sym_end,
      sym_timestamp,
  [300] = 3,
    ACTIONS(93), 1,
      aux_sym_value_token1,
    ACTIONS(95), 1,
      sym_comment,
    STATE(41), 1,
      sym_value,
  [310] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(50), 2,
      ts_builtin_sym_end,
      sym_timestamp,
  [318] = 3,
    ACTIONS(93), 1,
      aux_sym_value_token1,
    ACTIONS(95), 1,
      sym_comment,
    STATE(33), 1,
      sym_value,
  [328] = 3,
    ACTIONS(95), 1,
      sym_comment,
    ACTIONS(97), 1,
      aux_sym_value_token1,
    STATE(31), 1,
      sym_lyrics,
  [338] = 3,
    ACTIONS(93), 1,
      aux_sym_value_token1,
    ACTIONS(95), 1,
      sym_comment,
    STATE(34), 1,
      sym_value,
  [348] = 3,
    ACTIONS(93), 1,
      aux_sym_value_token1,
    ACTIONS(95), 1,
      sym_comment,
    STATE(36), 1,
      sym_value,
  [358] = 3,
    ACTIONS(93), 1,
      aux_sym_value_token1,
    ACTIONS(95), 1,
      sym_comment,
    STATE(43), 1,
      sym_value,
  [368] = 3,
    ACTIONS(93), 1,
      aux_sym_value_token1,
    ACTIONS(95), 1,
      sym_comment,
    STATE(44), 1,
      sym_value,
  [378] = 3,
    ACTIONS(93), 1,
      aux_sym_value_token1,
    ACTIONS(95), 1,
      sym_comment,
    STATE(37), 1,
      sym_value,
  [388] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(99), 1,
      ts_builtin_sym_end,
  [395] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(101), 1,
      sym__eol,
  [402] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(103), 1,
      anon_sym_RBRACK,
  [409] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(105), 1,
      anon_sym_RBRACK,
  [416] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(107), 1,
      anon_sym_RBRACK,
  [423] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(109), 1,
      anon_sym_RBRACK,
  [430] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(111), 1,
      anon_sym_RBRACK,
  [437] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(113), 1,
      anon_sym_RBRACK,
  [444] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(115), 1,
      sym_length_value,
  [451] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(117), 1,
      anon_sym_RBRACK,
  [458] = 2,
    ACTIONS(95), 1,
      sym_comment,
    ACTIONS(119), 1,
      aux_sym_value_token1,
  [465] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(121), 1,
      anon_sym_RBRACK,
  [472] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(123), 1,
      sym_offset_value,
  [479] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(125), 1,
      anon_sym_RBRACK,
  [486] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(127), 1,
      anon_sym_RBRACK,
  [493] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(129), 1,
      sym__eol,
  [500] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(131), 1,
      sym__eol,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 28,
  [SMALL_STATE(4)] = 56,
  [SMALL_STATE(5)] = 91,
  [SMALL_STATE(6)] = 107,
  [SMALL_STATE(7)] = 121,
  [SMALL_STATE(8)] = 137,
  [SMALL_STATE(9)] = 149,
  [SMALL_STATE(10)] = 165,
  [SMALL_STATE(11)] = 181,
  [SMALL_STATE(12)] = 193,
  [SMALL_STATE(13)] = 205,
  [SMALL_STATE(14)] = 217,
  [SMALL_STATE(15)] = 229,
  [SMALL_STATE(16)] = 241,
  [SMALL_STATE(17)] = 253,
  [SMALL_STATE(18)] = 265,
  [SMALL_STATE(19)] = 277,
  [SMALL_STATE(20)] = 289,
  [SMALL_STATE(21)] = 300,
  [SMALL_STATE(22)] = 310,
  [SMALL_STATE(23)] = 318,
  [SMALL_STATE(24)] = 328,
  [SMALL_STATE(25)] = 338,
  [SMALL_STATE(26)] = 348,
  [SMALL_STATE(27)] = 358,
  [SMALL_STATE(28)] = 368,
  [SMALL_STATE(29)] = 378,
  [SMALL_STATE(30)] = 388,
  [SMALL_STATE(31)] = 395,
  [SMALL_STATE(32)] = 402,
  [SMALL_STATE(33)] = 409,
  [SMALL_STATE(34)] = 416,
  [SMALL_STATE(35)] = 423,
  [SMALL_STATE(36)] = 430,
  [SMALL_STATE(37)] = 437,
  [SMALL_STATE(38)] = 444,
  [SMALL_STATE(39)] = 451,
  [SMALL_STATE(40)] = 458,
  [SMALL_STATE(41)] = 465,
  [SMALL_STATE(42)] = 472,
  [SMALL_STATE(43)] = 479,
  [SMALL_STATE(44)] = 486,
  [SMALL_STATE(45)] = 493,
  [SMALL_STATE(46)] = 500,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [11] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_header, 1, 0, 0),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_header_repeat1, 2, 0, 0),
  [15] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_header_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [18] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [20] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [22] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [24] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [26] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [28] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [30] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [32] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [34] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [36] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [38] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_header_repeat1, 1, 0, 0),
  [40] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_header_repeat1, 1, 0, 0),
  [42] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [44] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_id_tag, 1, 0, 0),
  [46] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_id_tag, 1, 0, 0),
  [48] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [50] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [52] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(24),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_title_tag, 4, 0, 0),
  [57] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_title_tag, 4, 0, 0),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_artist_tag, 4, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_artist_tag, 4, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_length_tag, 4, 0, 0),
  [65] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_length_tag, 4, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_author_tag, 4, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_author_tag, 4, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_album_tag, 4, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_album_tag, 4, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_offset_tag, 4, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_offset_tag, 4, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_by_tag, 4, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_by_tag, 4, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_lyricist_tag, 4, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_lyricist_tag, 4, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tool_tag, 4, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tool_tag, 4, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_header_repeat1, 2, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [95] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [99] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_time_tag, 2, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_value, 1, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [115] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tool_key, 1, 0, 0),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_lyrics, 1, 0, 0),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_lrc(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "lrc",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
